class PropertyModel {
  final int id;

  final String image;
  final String title;
  final String price;
  final String address;
  final String area;
  final int bed;
  final int bathroom;
  final int kitchen;

  PropertyModel({
    required this.id,
    required this.image,
    required this.title,
    required this.price,
    required this.address,
    required this.area,
    required this.bed,
    required this.bathroom,
    required this.kitchen,
  });

  static List<PropertyModel> properties = [
    PropertyModel(
      id: 1,
      image: 'assets/images/home1.png',
      title: 'Luxury Villa',
      price: '\$1,200,000',
      address: 'Los Angeles, CA',
      area: '3500 sqft',
      bed: 5,
      bathroom: 4,
      kitchen: 2,
    ),
    PropertyModel(
      id: 2,
      image: 'assets/images/home2.png',
      title: 'Modern Apartment',
      price: '\$850,000',
      address: 'New York, NY',
      area: '1200 sqft',
      bed: 3,
      bathroom: 2,
      kitchen: 1,
    ),
    PropertyModel(
      id: 3,
      image: 'assets/images/home3.png',
      title: 'Beach House',
      price: '\$2,300,000',
      address: 'Miami, FL',
      area: '4500 sqft',
      bed: 6,
      bathroom: 5,
      kitchen: 3,
    ),
    PropertyModel(
      id: 4,
      image: 'assets/images/home4.png',
      title: 'Cozy Cottage',
      price: '\$450,000',
      address: 'Portland, OR',
      area: '1000 sqft',
      bed: 2,
      bathroom: 1,
      kitchen: 1,
    ),
    PropertyModel(
      id: 5,
      image: 'assets/images/home5.png',
      title: 'Penthouse Suite',
      price: '\$3,500,000',
      address: 'Manhattan, NY',
      area: '5000 sqft',
      bed: 4,
      bathroom: 3,
      kitchen: 2,
    ),
    PropertyModel(
      id: 6,
      image: 'assets/images/home6.png',
      title: 'Mountain Cabin',
      price: '\$750,000',
      address: 'Aspen, CO',
      area: '2000 sqft',
      bed: 3,
      bathroom: 2,
      kitchen: 1,
    ),
    PropertyModel(
      id: 7,
      image: 'assets/images/home7.png',
      title: 'Urban Loft',
      price: '\$1,000,000',
      address: 'San Francisco, CA',
      area: '1500 sqft',
      bed: 2,
      bathroom: 2,
      kitchen: 1,
    ),
    PropertyModel(
      id: 8,
      image: 'assets/images/home8.png',
      title: 'Family House',
      price: '\$600,000',
      address: 'Dallas, TX',
      area: '2500 sqft',
      bed: 4,
      bathroom: 3,
      kitchen: 2,
    ),
    PropertyModel(
      id: 9,
      image: 'assets/images/home9.png',
      title: 'Lakefront Villa',
      price: '\$2,800,000',
      address: 'Lake Tahoe, CA',
      area: '4000 sqft',
      bed: 5,
      bathroom: 4,
      kitchen: 2,
    ),
    PropertyModel(
      id: 10,
      image: 'assets/images/home10.png',
      title: 'Suburban Home',
      price: '\$500,000',
      address: 'Seattle, WA',
      area: '1800 sqft',
      bed: 3,
      bathroom: 2,
      kitchen: 1,
    ),
    PropertyModel(
      id: 11,
      image: 'assets/images/home11.png',
      title: 'Modern Farmhouse',
      price: '\$900,000',
      address: 'Austin, TX',
      area: '3000 sqft',
      bed: 4,
      bathroom: 3,
      kitchen: 2,
    ),
    PropertyModel(
      id: 12,
      image: 'assets/images/home12.png',
      title: 'City Studio',
      price: '\$400,000',
      address: 'Chicago, IL',
      area: '900 sqft',
      bed: 1,
      bathroom: 1,
      kitchen: 1,
    ),
    PropertyModel(
      id: 13,
      image: 'assets/images/home13.png',
      title: 'Desert Retreat',
      price: '\$1,500,000',
      address: 'Phoenix, AZ',
      area: '3500 sqft',
      bed: 5,
      bathroom: 4,
      kitchen: 2,
    ),
    PropertyModel(
      id: 14,
      image: 'assets/images/home14.png',
      title: 'Seaside Bungalow',
      price: '\$2,000,000',
      address: 'San Diego, CA',
      area: '3000 sqft',
      bed: 4,
      bathroom: 3,
      kitchen: 2,
    ),
    PropertyModel(
      id: 15,
      image: 'assets/images/home15.png',
      title: 'Countryside Estate',
      price: '\$3,200,000',
      address: 'Napa Valley, CA',
      area: '5000 sqft',
      bed: 6,
      bathroom: 5,
      kitchen: 3,
    ),
  ];
}
